import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { auth } from '@/auth'
import './globals.css'
import LogoutButton from '@/components/LogoutButton'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  const session = await auth()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-sm mx-auto my-4 p-4 rounded-xl bg-green-300 text-center">
          {session?.user?.email ? (
            <div className="flex gap-2 justify-between items-center">
              <span>{session?.user?.email}</span>
              <LogoutButton />
            </div>
          ) : (
            'Guest'
          )}
        </div>
        {children}
      </body>
    </html>
  )
}

export default RootLayout
